[project]
name = "resume"
version = "0.1.0"
description = "Adam Setpen's resume"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "grip>=4.6.2",
    "markdown2>=2.5.3",
    "weasyprint>=65.1",
]
